language: php
php:
  - '5.3'
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install:
  - composer install
before_script: echo 'date.timezone = "Europe/Rome"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
