language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  # - hhvm
  - nightly

env:
  global:
    secure: "Xu2GCvGLPh7RduWf0TRz7MjAqnYS34tgEHBcUJmjLJLUeLnw4aIASHeQJ8TMrGrQtBa6uH/2Ur0YkTCLWdyR1ZHVpm2Iu7zrOZMdoy74NS7UOzSQqBj4B4pm2slTdQ5iKz5bmKXwDldIY4FYZiPaA1YmqAwSIqdYaEbk9fGuCg4PN6dmyBtM0IJ5a2IU5nf0gSt/QVgvn7OBdvsN7Tl9K58cgIXkYrRK5DXMXZ01tlaENIUWtHSMbB7bGt1/m9V4ShGQVZVFVM9pfeTvv2icGTKXdcNtlKqWajoKQFCEZ/8+Lg53FRcNYTsfBZjP/meBv15befgAy8UiinR+V7J7+ZDchafigzOu15o9svK9N10t91ziVCR2FypZdKfRqyV9kXNyo974Sf0Xz11PPK/SHIL+oxYk2uvbNGbCyTJE0BIu0t+nGEJhTS7cn71gXjyTptJTfAI05PJWHUoNOZ/iaGdgcw9R9yJlNlktKYvuDf9BqMTWXeb5Yo425qUiUi6lsOJbPIK4SYP//3FZCtKZY9m+RuPU0SvyeHMTDtguNQXO8Hff/+2MRbyvv5JaJfqyFDiWlVpyslha4e7xzkxXWr57zVdpSgWzjcPGnfP9QSoPteFtQGlqKZKSZpQi/WAR5F7igwdeIjVTz3p0f5p1sOqY5rnZJfGbntp8FBAOF0c="

notifications:
  slack:
    secure: lncKg9lLCPC8E20/vhl6iKkHCXPwLokLfpbcTutpQRvjEd/k+vzU4vBqVeiS5yqKa9/+E8ISz6Ax23QSHBDTdO9SYfFgYcQLSt0qQ61ERI5RyA7KJky8gXrSBmPF46T1lzTPP7JGRlwkIzh0V3txz259bx40oKPvIjiIAVu/oT7U5GX1zxeTgjkDqKFXK3RgWZtf+v5ro3DCYNMmapx3uq0f7BsdQe/M5RN8EXZEiSRHELb4aXneqU8JU4oGkL/BcM1hwzmvvUaYJ2I8Y55p7QKUABgV+D8KthZ2l+x//KB0hYwQxFnsVUrPWKcRiM29GBrLmfQ6ikrGlrwxVM9JhHPZztWB3sF1YybF2yMQoIP/oOYIHw41DvOdi5eOazms/OzRxrw7VWFH2gynAypposLrMAR5y0rURo7SLsEHELIZ6UHN5No2pf/q6tDYwDdLgqX28FR4skObvQHxKqzFtqMofAI0UrF8275zt+1dwqTEjOjwdycCT8hLFkEWGVHb06ObLdQFDv9dq79or3gtGOPP0c03uxmkldHGMV+7HWxc+6y8mVmKBJbLB9UxynvJtb1co1UaacznmbcSEPtE7QrN6pmgLsFXyrWcRjOoiB7BCHB/1cv13WuIUr+Q71DQBNx16pL+fRjNwnhqUO8myP1y8wee3+9BGs73+7LPZsU=

before_install:
  - sudo apt-get install -y graphviz
  # - printf "\n" | pecl install intl
  - phpenv config-add xsl.ini

install:
  - composer install

before_script:
  # phpDocumentor
  - mkdir -p docs
  # PHPUnit
  - mkdir -p coverage

after_success:
  - ./vendor/bin/phpdoc
  # phpDocumentor
  - bash .travis_after_script.sh
