language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  # - hhvm
  - nightly

env:
  global:
    secure: "epO3BlzVo37wDBlmXOi3rNXA/5ZLD/6Yk5BmFiQ5P4nbCEBlqB42Lr7xJvZldQdu6eSua/1plO89H2SJZjyod1PpzT3Stbs2j5MZGoLj0Qm1Q7AQbpnO+TNZH+qamn59vtngQln2duV3d5M+pog79NUZ3XUIsvJPUJfftkPNtMNyj61oS2owjddPnEdOlSO4eXhlVuJmTH4nqQSyvMCEBN2F3JS/WiuaF0a+7ZIoxC1CSC8HeyvZwAkxACKCN/s+4MQO1Sc9AKtNnFDQGZgE8zAAN3w63rtWyxA+6rPW1XCK0EiOyU5kpyXT0PDcq914cA3o0QY+0gaxvPqTJd4jqZzQwNWnFd8Y3jkFzYG4Ic9JQ2Swtq3t45rR5ipubWS9vZGiL3zWoJyoFR5N6MxtrnSQU1I+SQPJ4qtlVC2bMeu2LXL3SQeuQFwEvNLi47hbZwMr6mU4bgbVZlcdNEUT4iBeDZZUIgnNEpexnbVM60WGXF75mq5MUv1oTfmPtQyvLKCLdDJLRkt7cIFbWOSTb3fX5DTnS15ZJvBMd9mN5IPa6l2lst6IbihAAN5tjGer3o3xNTmMjX22RZ2Xo0cpBwJGsvtPwQ932He5iVGFyJH8JNtj82KGTXYdmI9Uj1WMUFig9zgqZdisR36bctqd9UeF7pEsM0wsJy3o2DtQRBA="

notifications:
  slack:
    secure: lncKg9lLCPC8E20/vhl6iKkHCXPwLokLfpbcTutpQRvjEd/k+vzU4vBqVeiS5yqKa9/+E8ISz6Ax23QSHBDTdO9SYfFgYcQLSt0qQ61ERI5RyA7KJky8gXrSBmPF46T1lzTPP7JGRlwkIzh0V3txz259bx40oKPvIjiIAVu/oT7U5GX1zxeTgjkDqKFXK3RgWZtf+v5ro3DCYNMmapx3uq0f7BsdQe/M5RN8EXZEiSRHELb4aXneqU8JU4oGkL/BcM1hwzmvvUaYJ2I8Y55p7QKUABgV+D8KthZ2l+x//KB0hYwQxFnsVUrPWKcRiM29GBrLmfQ6ikrGlrwxVM9JhHPZztWB3sF1YybF2yMQoIP/oOYIHw41DvOdi5eOazms/OzRxrw7VWFH2gynAypposLrMAR5y0rURo7SLsEHELIZ6UHN5No2pf/q6tDYwDdLgqX28FR4skObvQHxKqzFtqMofAI0UrF8275zt+1dwqTEjOjwdycCT8hLFkEWGVHb06ObLdQFDv9dq79or3gtGOPP0c03uxmkldHGMV+7HWxc+6y8mVmKBJbLB9UxynvJtb1co1UaacznmbcSEPtE7QrN6pmgLsFXyrWcRjOoiB7BCHB/1cv13WuIUr+Q71DQBNx16pL+fRjNwnhqUO8myP1y8wee3+9BGs73+7LPZsU=

before_install:
  - sudo apt-get install -y graphviz
  # - printf "\n" | pecl install intl
  - phpenv config-add xsl.ini

install:
  - composer install

before_script:
  # phpDocumentor
  - mkdir -p docs
  # PHPUnit
  - mkdir -p coverage

after_success:
  - ./vendor/bin/phpdoc
  # phpDocumentor
  - bash .travis_after_script.sh
